[package]
name = "skylord-103/datastore-wrapper"
description = "A simplified wrapper for Roblox data stores"
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
